// begin Core.Agent.TicketAction.js
"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketAction=(function(TargetNS){function SerializeData(Data){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});return QueryString;}
function OpenSpellChecker(){var SpellCheckIFrame,SpellCheckIFrameURL;SpellCheckIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AgentSpelling;Field=RichText;Body='+encodeURIComponent($('#RichText').val());SpellCheckIFrameURL+=SerializeData(Core.App.GetSessionInformation());SpellCheckIFrame='<iframe class="TextOption SpellCheck" src="'+SpellCheckIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(SpellCheckIFrame,'','10px','Center',true);}
function OpenAddressBook(){var AddressBookIFrameURL,AddressBookIFrame;AddressBookIFrameURL=Core.Config.Get('CGIHandle')+
'?Action=AgentBook;ToCustomer='+encodeURIComponent($('#CustomerAutoComplete, #ToCustomer').val())+
';CcCustomer='+encodeURIComponent($('#Cc, #CcCustomer').val())+
';BccCustomer='+encodeURIComponent($('#Bcc, #BccCustomer').val());AddressBookIFrameURL+=SerializeData(Core.App.GetSessionInformation());AddressBookIFrame='<iframe class="TextOption" src="'+AddressBookIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(AddressBookIFrame,'','10px','Center',true);}
function OpenCustomerDialog(){var CustomerIFrameURL,CustomerIFrame;CustomerIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AdminCustomerUser;Nav=None;Subject=;What=';CustomerIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerIFrame='<iframe class="TextOption Customer" src="'+CustomerIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerIFrame,'','10px','Center',true);}
function AddMailAddress($Link){var $Element=$('#'+$Link.attr('rel')),NewValue=$Element.val();if(NewValue.length){NewValue=NewValue+', ';}
NewValue=NewValue+Core.Data.Get($Link.closest('tr'),'Email');$Element.val(NewValue);}
function MarkPrimaryCustomer(){$('.CustomerContainer').children('div').each(function(){var $InputObj=$(this).find('.CustomerTicketText'),$RadioObj=$(this).find('.CustomerTicketRadio');if($RadioObj.prop('checked')){$InputObj.addClass('MainCustomer');}
else{$InputObj.removeClass('MainCustomer');}});}
TargetNS.Init=function(){$('#OptionSpellCheck').bind('click',function(Event){OpenSpellChecker();return false;});$('#OptionAddressBook').bind('click',function(Event){OpenAddressBook();return false;});$('#OptionCustomer').bind('click',function(Event){OpenCustomerDialog();return false;});MarkPrimaryCustomer();Core.App.Subscribe('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',function(){MarkPrimaryCustomer();});$('#submitRichText').on('click',function(Event){var ToCustomer=$('#ToCustomer').val()||'',CcCustomer=$('#CcCustomer').val()||'',BccCustomer=$('#BccCustomer').val()||'',FromCustomer=$('#FromCustomer').val()||'';if(ToCustomer.length||CcCustomer.length||BccCustomer.length||FromCustomer.length){window.setTimeout(function(){$('#submitRichText').trigger('click');},100);Event.preventDefault();Event.stopPropagation();return false;}});};TargetNS.InitAddressBook=function(){$('#SearchResult a').bind('click',function(Event){AddMailAddress($(this));return false;});$('#Apply').bind('click',function(Event){var $To,$Cc,$Bcc;if($('#CustomerAutoComplete',parent.document).length){$To=$('#CustomerAutoComplete',parent.document);$Cc=$('#Cc',parent.document);$Bcc=$('#Bcc',parent.document);$To.val($('#ToCustomer').val());$Cc.val($('#CcCustomer').val());$Bcc.val($('#BccCustomer').val());}
else{$To=$('#ToCustomer',parent.document);$Cc=$('#CcCustomer',parent.document);$Bcc=$('#BccCustomer',parent.document);$.each($('#ToCustomer').val().split(/, ?/),function(Index,Value){$To.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('ToCustomer',Value);});$.each($('#CcCustomer').val().split(/, ?/),function(Index,Value){$Cc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('CcCustomer',Value);});$.each($('#BccCustomer').val().split(/, ?/),function(Index,Value){$Bcc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('BccCustomer',Value);});}
parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(Event){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.InitSpellCheck=function(){$('#SpellCheck select, #SpellCheck input:text').bind('change',function(Event){var $Row=$(this).closest('tr'),RowCount=parseInt($Row.attr('id').replace(/Row/,''),10);$Row.find('input:radio[id=ChangeWord'+RowCount+']').prop('checked',true);});$('#Apply').bind('click',function(Event){var FieldName=$('#Field').val(),$Body=$('#'+FieldName,parent.document);$Body.val($('#Body').val());parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(Event){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.UpdateCustomer=function(Customer){var $UpdateForm=$('form[name=compose]',parent.document);$UpdateForm
.find('#ExpandCustomerName').val('2')
.end()
.find('#PreSelectedCustomerUser').val(Customer)
.end()
.submit();parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));};TargetNS.SelectRadioButton=function(Value,Name){$('input:radio[name='+Name+'][value='+Value+']').prop('checked',true);};return TargetNS;}(Core.Agent.TicketAction||{}));
// end Core.Agent.TicketAction.js
