// begin Core.Agent.CustomerSearch.js
"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.CustomerSearch=(function(TargetNS){var BackupData={CustomerInfo:'',CustomerEmail:'',CustomerKey:''},CustomerFieldChangeRunCount={};function GetCustomerInfo(CustomerUserID){var Data={Action:'AgentCustomerSearch',Subaction:'CustomerInfo',CustomerUserID:CustomerUserID||1};Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){$('#CustomerID').val(Response.CustomerID);$('#ShowCustomerID').html(Response.CustomerID);Core.App.Publish('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',[Response.CustomerID]);$('#CustomerInfo .Content').html(Response.CustomerTableHTMLString);if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketPhone'){$('#ServiceID').attr('selectedIndex',0);Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',['Dest','SelectedCustomerUser','NextStateID','PriorityID','ServiceID','SLAID','CryptKeyID','OwnerAll','ResponsibleAll','TicketFreeText1','TicketFreeText2','TicketFreeText3','TicketFreeText4','TicketFreeText5','TicketFreeText6','TicketFreeText7','TicketFreeText8','TicketFreeText9','TicketFreeText10','TicketFreeText11','TicketFreeText12','TicketFreeText13','TicketFreeText14','TicketFreeText15','TicketFreeText16']);}
if(Core.Config.Get('Action')==='AgentTicketProcess'){$('#ServiceID').attr('selectedIndex',0);Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',Core.Config.Get('ProcessManagement.UpdatableFields'));}});}
function GetCustomerTickets(CustomerUserID,CustomerID){if(!parseInt(Core.Config.Get('CustomerSearch.ShowCustomerTickets'),10)){return;}
var Data={Action:'AgentCustomerSearch',Subaction:'CustomerTickets',CustomerUserID:CustomerUserID,CustomerID:CustomerID};function ReplaceCustomerTicketLinks(){var ResizeTimeoutWindow;$('#CustomerTickets').find('.AriaRoleMain').removeAttr('role').removeClass('AriaRoleMain');$('#CustomerTickets').find('.OverviewZoom a, .Pagination a, .TableSmall th a').click(function(){var Link=$(this).attr('href'),URLComponents;URLComponents=Link.split('?',2);Core.AJAX.FunctionCall(URLComponents[0],URLComponents[1],function(Response){if($('#CustomerTickets').length){$('#CustomerTickets').html(Response.CustomerTicketsHTMLString);ReplaceCustomerTicketLinks();}});return false;});Core.UI.Accordion.Init($('.Preview > ul'),'li h3 a','.HiddenBlock');if($('#TicketList table').length){Core.UI.Table.InitCSSPseudoClasses();}
if(Core.Config.Get('Action')==='AgentTicketCustomer'){$('a.MasterActionLink').bind('click',function(){window.opener.Core.UI.Popup.FirePopupEvent('URL',{URL:this.href});window.close();return false;});}
return false;}
Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){if($('#CustomerTickets').length){$('#CustomerTickets').html(Response.CustomerTicketsHTMLString);ReplaceCustomerTicketLinks();}});}
function CheckPhoneCustomerCountLimit(){if(Core.Config.Get('Action')!=='AgentTicketPhone'){return;}
if(Core.Config.Get('Ticket::Frontend::AgentTicketPhone::AllowMultipleFrom')==="1"){return;}
if($('#TicketCustomerContentFromCustomer input.CustomerTicketText').length>0){$('#FromCustomer').val('').prop('disabled',true).prop('readonly',true);$('#Dest').trigger('focus');}
else{$('#FromCustomer').val('').prop('disabled',false).prop('readonly',false);}}
TargetNS.Init=function($Element){if(Core.Config.Get('Action')==='AgentTicketCustomer'){GetCustomerTickets($('#CustomerAutoComplete').val(),$('#CustomerID').val());}
if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketPhone')&&$('#SelectedCustomerUser').val()!==''){GetCustomerTickets($('#SelectedCustomerUser').val());}
if($('#CustomerInfo').length){BackupData.CustomerInfo=$('#CustomerInfo .Content').html();}
if(isJQueryObject($Element)){$Element.unbind('keyup.Validate').bind('keyup.Validate',function(){var Value=$Element.val();if($Element.hasClass('ServerError')&&Value.length){$('#OTRS_UI_Tooltips_ErrorTooltip').hide();}});Core.UI.Autocomplete.Init($Element,function(Request,Response){var URL=Core.Config.Get('Baselink'),Data={Action:'AgentCustomerSearch',Term:Request.term,MaxResults:Core.UI.Autocomplete.GetConfig('MaxResultsDisplayed')};$Element.data('AutoCompleteXHR',Core.AJAX.FunctionCall(URL,Data,function(Result){var Data=[];$Element.removeData('AutoCompleteXHR');$.each(Result,function(){Data.push({label:this.CustomerValue+" ("+this.CustomerKey+")",value:this.CustomerValue,key:this.CustomerKey});});Response(Data);}));},function(Event,UI){var CustomerKey=UI.item.key,CustomerValue=UI.item.value;BackupData.CustomerKey=CustomerKey;BackupData.CustomerEmail=CustomerValue;if(Core.Config.Get('Action')==='AgentBook'){$('#'+$(this).attr('id')).val(CustomerValue);return false;}
$Element.val(CustomerValue);if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'){$Element.val('');}
if(Core.Config.Get('Action')!=='AgentTicketPhone'&&Core.Config.Get('Action')!=='AgentTicketEmail'&&Core.Config.Get('Action')!=='AgentTicketCompose'&&Core.Config.Get('Action')!=='AgentTicketForward'){$('#SelectedCustomerUser').val(CustomerKey);if($('#CustomerUserID').length){$('#CustomerUserID').val(CustomerKey);if($('#CustomerUserOption').length){$('#CustomerUserOption').val(CustomerKey);}
else{$('<input type="hidden" name="CustomerUserOption" id="CustomerUserOption">').val(CustomerKey).appendTo($Element.closest('form'));}}
GetCustomerTickets(CustomerKey);GetCustomerInfo(CustomerKey);}
else{TargetNS.AddTicketCustomer($(Event.target).attr('id'),CustomerValue,CustomerKey);}},'CustomerSearch');if(Core.Config.Get('Action')!=='AgentTicketPhone'&&Core.Config.Get('Action')!=='AgentTicketEmail'&&Core.Config.Get('Action')!=='AgentTicketCompose'&&Core.Config.Get('Action')!=='AgentTicketForward'){$Element.blur(function(){var FieldValue=$(this).val();if(FieldValue!==BackupData.CustomerEmail&&FieldValue!==BackupData.CustomerKey){$('#SelectedCustomerUser').val('');$('#CustomerUserID').val('');$('#CustomerID').val('');$('#CustomerUserOption').val('');$('#ShowCustomerID').html('');$('#CustomerInfo .Content').html(BackupData.CustomerInfo);if(Core.Config.Get('Action')==='AgentTicketProcess'){Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',Core.Config.Get('ProcessManagement.UpdatableFields'));}}});}
else{TargetNS.InitCustomerField();}}
$(window).bind('unload',function(){$('#SelectedCustomerUser').val('');});CheckPhoneCustomerCountLimit();};TargetNS.AddTicketCustomer=function(Field,CustomerValue,CustomerKey,SetAsTicketCustomer){if(CustomerValue===''){return false;}
var $Clone=$('.CustomerTicketTemplate'+Field).clone(),CustomerTicketCounter=$('#CustomerTicketCounter'+Field).val(),TicketCustomerIDs=0,IsDuplicated=false,Suffix;$('[class*=CustomerTicketText]').each(function(index){if($(this).val()===CustomerValue){IsDuplicated=true;}});if(IsDuplicated){TargetNS.ShowDuplicatedDialog(Field);return false;}
TicketCustomerIDs=$('.CustomerContainer input:radio').length;CustomerTicketCounter++;Suffix='_'+CustomerTicketCounter;$Clone.removeClass('Hidden CustomerTicketTemplate'+Field);$Clone.find(':input').each(function(){var ID=$(this).attr('id');$(this).attr('id',ID+Suffix);$(this).val(CustomerValue);if(ID!=='CustomerSelected'){$(this).attr('name',ID+Suffix);}
if($(this).hasClass('CustomerTicketRadio')){if(TicketCustomerIDs===0){$(this).prop('checked',true);}
$(this).val(CustomerTicketCounter);$(this).bind('change',function(){if($(this).prop('checked')){TargetNS.ReloadCustomerInfo(CustomerKey);}
return false;});}
if($(this).hasClass('CustomerKey')){$(this).val(CustomerKey);}
if($(this).hasClass('Remove')){$(this).bind('click',function(){TargetNS.RemoveCustomerTicket($(this));return false;});$(this).val(CustomerValue);}});$('#TicketCustomerContent'+Field).parent().removeClass('Hidden');$('#TicketCustomerContent'+Field).append($Clone);$('#CustomerTicketCounter'+Field).val(CustomerTicketCounter);if((CustomerKey!==''&&TicketCustomerIDs===0&&(Field==='ToCustomer'||Field==='FromCustomer'))||SetAsTicketCustomer){if(SetAsTicketCustomer){$('#CustomerSelected_'+CustomerTicketCounter).prop('checked',true).trigger('change');}
else{$('.CustomerContainer input:radio:first').prop('checked',true).trigger('change');}}
$('#'+Field).val('').focus();CheckPhoneCustomerCountLimit();if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward')&&$('#CryptKeyID').length){Core.AJAX.FormUpdate($('#'+Field).closest('form'),'AJAXUpdate','',['CryptKeyID']);}
return false;};TargetNS.RemoveCustomerTicket=function(Object){var TicketCustomerIDs=0,TicketCustomerIDsCounter=0,ObjectoToCheck,$Field=Object.closest('.Field'),$Form;if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'){$Form=Object.closest('form');}
Object.parent().remove();TicketCustomerIDs=$('.CustomerContainer input:radio').length;if(TicketCustomerIDs===0){TargetNS.ResetCustomerInfo();}
if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward')&&$('#CryptKeyID').length){Core.AJAX.FormUpdate($Form,'AJAXUpdate','',['CryptKeyID']);}
if(!$('.CustomerContainer input:radio').is(':checked')){$('.CustomerContainer input:radio:first').prop('checked',true).trigger('change');}
if($Field.find('.CustomerTicketText:visible').length===0){$Field.addClass('Hidden');}
CheckPhoneCustomerCountLimit();};TargetNS.ResetCustomerInfo=function(){$('#SelectedCustomerUser').val('');$('#CustomerUserID').val('');$('#CustomerID').val('');$('#CustomerUserOption').val('');$('#ShowCustomerID').html('');$('#CustomerInfo .Content').html('none');};TargetNS.ReloadCustomerInfo=function(CustomerKey){GetCustomerTickets(CustomerKey);GetCustomerInfo(CustomerKey);$('#SelectedCustomerUser').val(CustomerKey);};TargetNS.InitCustomerField=function(){$('.CustomerAutoComplete').each(function(index){var ObjectId=$(this).attr('id');$('#'+ObjectId).bind('change',function(){if(!$('#'+ObjectId).val()||$('#'+ObjectId).val()===''){return false;}
if(!Core.UI.Autocomplete.GetConfig('ActiveAutoComplete')){if(typeof CustomerFieldChangeRunCount[ObjectId]==='undefined'){CustomerFieldChangeRunCount[ObjectId]=1;}
else{CustomerFieldChangeRunCount[ObjectId]++;}
if(Core.UI.Autocomplete.SearchButtonClicked[ObjectId]){delete CustomerFieldChangeRunCount[ObjectId];delete Core.UI.Autocomplete.SearchButtonClicked[ObjectId];return false;}
else{if(CustomerFieldChangeRunCount[ObjectId]===1){window.setTimeout(function(){$('#'+ObjectId).trigger('change');},200);return false;}
delete CustomerFieldChangeRunCount[ObjectId];}}
if($(this).autocomplete("widget").is(':visible')){window.setTimeout(function(){$('#'+ObjectId).trigger('change');},200);return false;}
Core.Agent.CustomerSearch.AddTicketCustomer(ObjectId,$('#'+ObjectId).val());return false;});$('#'+ObjectId).bind('keypress',function(e){if(e.which===13){Core.Agent.CustomerSearch.AddTicketCustomer(ObjectId,$('#'+ObjectId).val());return false;}});});};TargetNS.ShowDuplicatedDialog=function(Field){Core.UI.Dialog.ShowAlert(Core.Config.Get('Duplicated.TitleText'),Core.Config.Get('Duplicated.ContentText')+' '+Core.Config.Get('Duplicated.RemoveText'),function(){Core.UI.Dialog.CloseDialog($('.Alert'));$('#'+Field).val('');$('#'+Field).focus();return false;});};return TargetNS;}(Core.Agent.CustomerSearch||{}));
// end Core.Agent.CustomerSearch.js
// begin Core.Agent.TicketAction.js
"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketAction=(function(TargetNS){function SerializeData(Data){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});return QueryString;}
function OpenSpellChecker(){var SpellCheckIFrame,SpellCheckIFrameURL;SpellCheckIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AgentSpelling;Field=RichText;Body='+encodeURIComponent($('#RichText').val());SpellCheckIFrameURL+=SerializeData(Core.App.GetSessionInformation());SpellCheckIFrame='<iframe class="TextOption SpellCheck" src="'+SpellCheckIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(SpellCheckIFrame,'','10px','Center',true);}
function OpenAddressBook(){var AddressBookIFrameURL,AddressBookIFrame;AddressBookIFrameURL=Core.Config.Get('CGIHandle')+
'?Action=AgentBook;ToCustomer='+encodeURIComponent($('#CustomerAutoComplete, #ToCustomer').val())+
';CcCustomer='+encodeURIComponent($('#Cc, #CcCustomer').val())+
';BccCustomer='+encodeURIComponent($('#Bcc, #BccCustomer').val());AddressBookIFrameURL+=SerializeData(Core.App.GetSessionInformation());AddressBookIFrame='<iframe class="TextOption" src="'+AddressBookIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(AddressBookIFrame,'','10px','Center',true);}
function OpenCustomerDialog(){var CustomerIFrameURL,CustomerIFrame;CustomerIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AdminCustomerUser;Nav=None;Subject=;What=';CustomerIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerIFrame='<iframe class="TextOption Customer" src="'+CustomerIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerIFrame,'','10px','Center',true);}
function AddMailAddress($Link){var $Element=$('#'+$Link.attr('rel')),NewValue=$Element.val();if(NewValue.length){NewValue=NewValue+', ';}
NewValue=NewValue+Core.Data.Get($Link.closest('tr'),'Email');$Element.val(NewValue);}
function MarkPrimaryCustomer(){$('.CustomerContainer').children('div').each(function(){var $InputObj=$(this).find('.CustomerTicketText'),$RadioObj=$(this).find('.CustomerTicketRadio');if($RadioObj.prop('checked')){$InputObj.addClass('MainCustomer');}
else{$InputObj.removeClass('MainCustomer');}});}
TargetNS.Init=function(){$('#OptionSpellCheck').bind('click',function(Event){OpenSpellChecker();return false;});$('#OptionAddressBook').bind('click',function(Event){OpenAddressBook();return false;});$('#OptionCustomer').bind('click',function(Event){OpenCustomerDialog();return false;});MarkPrimaryCustomer();Core.App.Subscribe('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',function(){MarkPrimaryCustomer();});$('#submitRichText').on('click',function(Event){var ToCustomer=$('#ToCustomer').val()||'',CcCustomer=$('#CcCustomer').val()||'',BccCustomer=$('#BccCustomer').val()||'',FromCustomer=$('#FromCustomer').val()||'';if(ToCustomer.length||CcCustomer.length||BccCustomer.length||FromCustomer.length){window.setTimeout(function(){$('#submitRichText').trigger('click');},100);Event.preventDefault();Event.stopPropagation();return false;}});};TargetNS.InitAddressBook=function(){$('#SearchResult a').bind('click',function(Event){AddMailAddress($(this));return false;});$('#Apply').bind('click',function(Event){var $To,$Cc,$Bcc;if($('#CustomerAutoComplete',parent.document).length){$To=$('#CustomerAutoComplete',parent.document);$Cc=$('#Cc',parent.document);$Bcc=$('#Bcc',parent.document);$To.val($('#ToCustomer').val());$Cc.val($('#CcCustomer').val());$Bcc.val($('#BccCustomer').val());}
else{$To=$('#ToCustomer',parent.document);$Cc=$('#CcCustomer',parent.document);$Bcc=$('#BccCustomer',parent.document);$.each($('#ToCustomer').val().split(/, ?/),function(Index,Value){$To.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('ToCustomer',Value);});$.each($('#CcCustomer').val().split(/, ?/),function(Index,Value){$Cc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('CcCustomer',Value);});$.each($('#BccCustomer').val().split(/, ?/),function(Index,Value){$Bcc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('BccCustomer',Value);});}
parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(Event){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.InitSpellCheck=function(){$('#SpellCheck select, #SpellCheck input:text').bind('change',function(Event){var $Row=$(this).closest('tr'),RowCount=parseInt($Row.attr('id').replace(/Row/,''),10);$Row.find('input:radio[id=ChangeWord'+RowCount+']').prop('checked',true);});$('#Apply').bind('click',function(Event){var FieldName=$('#Field').val(),$Body=$('#'+FieldName,parent.document);$Body.val($('#Body').val());parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(Event){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.UpdateCustomer=function(Customer){var $UpdateForm=$('form[name=compose]',parent.document);$UpdateForm
.find('#ExpandCustomerName').val('2')
.end()
.find('#PreSelectedCustomerUser').val(Customer)
.end()
.submit();parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));};TargetNS.SelectRadioButton=function(Value,Name){$('input:radio[name='+Name+'][value='+Value+']').prop('checked',true);};return TargetNS;}(Core.Agent.TicketAction||{}));
// end Core.Agent.TicketAction.js
